version: "3.9"
services:
  app:
    build:
      context: app
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "81:80"